'use client';

import { ArrowLeft } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[var(--bg-primary)] px-4 py-12">
      <div className="max-w-2xl mx-auto">
        <a href="/login" className="inline-flex items-center gap-1.5 text-sm text-[var(--text-muted)] hover:text-[var(--text-secondary)] transition-colors mb-8">
          <ArrowLeft className="w-4 h-4" />
          Back
        </a>

        <div className="bg-[var(--card-bg)] border border-[var(--card-border)] rounded-2xl p-8 space-y-6" style={{ boxShadow: 'var(--card-shadow-elevated)' }}>
          <div className="space-y-2">
            <h1 className="text-2xl font-bold text-[var(--text-primary)]">Terms of Service</h1>
            <p className="text-sm text-[var(--text-muted)]">Last updated: March 19, 2026</p>
          </div>

          <div className="space-y-5 text-sm text-[var(--text-secondary)] leading-relaxed">
            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">1. Acceptance of Terms</h2>
              <p>
                By accessing or using My Patient Dashboard (&quot;the Application&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Application. The Application is operated by Aaron Gropper, MD (&quot;the Developer&quot;).
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">2. Description of Service</h2>
              <p>
                My Patient Dashboard is a clinical documentation and workflow tool designed for physicians. The Application integrates with Google services to provide data storage and authentication. It is currently provided on a beta basis for testing and evaluation purposes.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">3. Eligibility and Access</h2>
              <p>
                The Application is intended for use by licensed healthcare professionals. Access is granted on an invitation-only basis and may be revoked at any time at the sole discretion of the Developer. You must authenticate using a valid Google account to use the Application.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">4. User Responsibilities</h2>
              <p>You agree to:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Provide your own API keys for third-party AI and transcription services as required.</li>
                <li>Use the Application in compliance with all applicable laws, regulations, and professional standards, including patient privacy and data protection requirements.</li>
                <li>Not share your account credentials or allow unauthorized access to the Application.</li>
                <li>Accept full responsibility for any clinical decisions made using information generated by the Application.</li>
              </ul>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">5. Intellectual Property</h2>
              <p>
                All source code, designs, concepts, features, algorithms, and intellectual property embodied in the Application are the exclusive property of Aaron Gropper, MD. Access to the Application does not grant any ownership, license, or rights to the underlying technology, code, or proprietary concepts. You agree not to reverse-engineer, copy, distribute, or create derivative works based on the Application.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">6. Data and Privacy</h2>
              <p>
                Patient data you enter is stored in your own Google Sheet within your Google account. The Developer does not access, store, or have visibility into your patient data. Session information and user preferences are stored securely using encrypted, server-side storage. For full details, see our <a href="/privacy" className="text-teal-600 hover:underline">Privacy Policy</a>.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">7. Third-Party Services</h2>
              <p>
                The Application integrates with third-party services including Google (authentication, Sheets), Anthropic (AI processing), OpenAI (transcription), and Deepgram (medical transcription). Your use of these services is governed by their respective terms of service and privacy policies. The Developer is not responsible for the availability, accuracy, or conduct of third-party services.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">8. No Medical Warranty</h2>
              <p>
                The Application is a documentation tool and is not intended to replace clinical judgment, established medical practice, or professional medical advice. AI-generated content (notes, suggestions, calculations) should always be reviewed and verified by a qualified healthcare professional before use in patient care. The Developer assumes no liability for clinical decisions or patient outcomes related to the use of this Application.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">9. Disclaimer of Warranties</h2>
              <p>
                The Application is provided &quot;as is&quot; and &quot;as available&quot; without warranty of any kind, express or implied. The Developer does not warrant that the Application will be uninterrupted, error-free, or free of bugs. Features may change, be added, or be removed without notice.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">10. Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, the Developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of data, profits, or revenue, arising out of or related to your use of the Application.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">11. Confidentiality</h2>
              <p>
                As the Application is in beta, you agree to treat its features, functionality, and design as confidential. You agree not to share screenshots, descriptions of functionality, or underlying concepts without prior written consent from the Developer.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">12. Termination</h2>
              <p>
                The Developer may suspend or terminate your access to the Application at any time, for any reason, without prior notice. Upon termination, your right to use the Application ceases immediately. Your data stored in your own Google account remains yours.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">13. Changes to Terms</h2>
              <p>
                The Developer reserves the right to modify these Terms at any time. Continued use of the Application after changes constitutes acceptance of the updated Terms.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-semibold text-[var(--text-primary)]">14. Contact</h2>
              <p>
                For questions about these Terms, contact Aaron Gropper, MD at <a href="mailto:aaron@gropper.me" className="text-teal-600 hover:underline">aaron@gropper.me</a>.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
