/**
 * Shorthand medical documentation phrases for ED encounter autocomplete.
 * All lowercase for suffix-aware matching in AutocompleteTextarea.
 *
 * These use standard ED physician abbreviations and shorthand
 * (e.g., "pt" = patient, "hx" = history, "dx" = diagnosis, "tx" = treatment).
 */
export const MEDICAL_SUGGESTIONS: string[] = [
  // ── General / Appearance ──
  "pt appears well",
  "pt appears well, nad",
  "pt appears unwell",
  "pt ill-appearing",
  "pt in nad",
  "pt in mild distress",
  "pt in moderate distress",
  "pt in severe distress",
  "pt a&o x3",
  "pt a&o x4",
  "pt alert and oriented",
  "gcs 15",
  "gcs 14",
  "avss",
  "vs wnl",
  "vs stable",
  "vs repeated and stable",
  "hemodynamically stable",
  "afebrile",

  // ── HPI / Presenting complaint ──
  "pt c/o",
  "pt presents c/o",
  "pt presents w/",
  "pt reports",
  "pt states",
  "pt brought in by ems",
  "pt brought in by family",
  "hx of present illness",
  "sx began approx",
  "sx x",
  "sx worsening",
  "sx intermittent",
  "sx constant",
  "sudden onset",
  "gradual onset",
  "acute onset",
  "no precipitating event",

  // ── Pain ──
  "sharp pain",
  "dull aching pain",
  "burning pain",
  "pressure-like pain",
  "crampy pain",
  "tearing pain",
  "throbbing pain",
  "colicky pain",
  "pleuritic pain",
  "pain radiates to",
  "pain worse w/ movement",
  "pain worse w/ deep breath",
  "pain relieved w/ rest",
  "pain relieved w/ analgesics",
  "pain non-radiating",
  "pain at rest",
  "pain w/ exertion",
  "ttp over",
  "no ttp",

  // ── Associated sx / pertinent negatives ──
  "assoc n/v",
  "assoc n+v",
  "assoc sob",
  "assoc fever/chills",
  "assoc diaphoresis",
  "assoc dizziness",
  "assoc palpitations",
  "assoc cough",
  "assoc diarrhea",
  "denies cp",
  "denies sob",
  "denies n/v",
  "denies fever/chills",
  "denies ha",
  "denies loc",
  "denies syncope",
  "denies dysuria",
  "denies hematuria",
  "denies numbness/tingling",
  "denies weakness",
  "denies rash",
  "denies trauma",
  "denies recent travel",
  "denies sick contacts",
  "no similar episodes prev",
  "hx of similar episodes",
  "tried otc meds w/o relief",

  // ── PMHx ──
  "pmhx sig for",
  "pmhx includes",
  "no sig pmhx",
  "hx htn",
  "hx dm2",
  "hx dm1",
  "hx cad",
  "hx mi",
  "hx afib",
  "hx copd",
  "hx asthma",
  "hx ckd",
  "hx chf",
  "hx cva",
  "hx tia",
  "hx dvt",
  "hx pe",
  "hx anxiety/depression",
  "hx gerd",
  "hx seizure d/o",
  "hx migraines",
  "hx oa",
  "hx ra",
  "hx gout",
  "hx etoh use",
  "hx substance use",
  "pshx includes",
  "s/p appy",
  "s/p chole",
  "s/p cabg",
  "s/p pci",
  "no prior surgeries",

  // ── Meds / Allergies ──
  "meds as per list",
  "on anticoag",
  "on antiplatelet",
  "on insulin",
  "on oha",
  "on antihtn",
  "on bb",
  "on acei",
  "on statin",
  "nkda",
  "allergy pcn",
  "allergy sulfa",
  "allergy nsaids",
  "allergy codeine",
  "allergy morphine",

  // ── Social Hx ──
  "non-smoker",
  "current smoker",
  "ex-smoker",
  "social etoh",
  "denies etoh",
  "denies rec drugs",
  "lives independently",
  "lives w/ family",
  "independent w/ adls",
  "requires assist w/ adls",
  "ltc resident",
  "uses walking aid",

  // ── HEENT ──
  "heent: ncat",
  "perrl",
  "perrl, eomi",
  "eomi",
  "tms clear bilat",
  "op clear, no erythema",
  "pharynx erythematous",
  "pharynx erythematous w/ exudate",
  "mmm",
  "mm dry",
  "no oral lesions",
  "no facial asymmetry",

  // ── Neck ──
  "neck: supple, no lad",
  "no meningismus",
  "trachea midline",
  "no jvd",
  "jvd present",
  "c-spine nt",
  "c-spine midline ttp",
  "full rom c-spine",

  // ── CVS ──
  "cvs: s1s2, rrr, no m/r/g",
  "s1s2 normal",
  "rrr",
  "irregularly irregular",
  "afib w/ rvr",
  "afib rate controlled",
  "systolic murmur",
  "no m/r/g",
  "periph pulses intact bilat",
  "cr < 2s",
  "cr < 3s",
  "no periph edema",
  "bilat le edema",
  "1+ pedal edema bilat",
  "2+ pedal edema bilat",
  "no calf ttp",
  "warm, well-perfused",

  // ── Resp ──
  "resp: ctab",
  "ctab",
  "good ae bilat",
  "equal ae bilat",
  "decreased ae bilat",
  "decreased ae l base",
  "decreased ae r base",
  "bilat wheeze",
  "diffuse wheeze",
  "fine crackles bilat bases",
  "coarse crackles bilat",
  "rhonchi bilat",
  "stridor",
  "no resp distress",
  "mild resp distress",
  "mod resp distress",
  "using accessory muscles",
  "comfortable on ra",
  "sats maintained on ra",
  "sats improved w/ o2",
  "on np",
  "on nrb",
  "chest expansion symmetric",
  "no cw ttp",
  "reproducible cw ttp",

  // ── Abdo ──
  "abdo: soft, nt, nd",
  "abdo soft, nt",
  "abdo distended",
  "rlq ttp",
  "llq ttp",
  "ruq ttp",
  "luq ttp",
  "epigastric ttp",
  "suprapubic ttp",
  "diffuse abdo ttp",
  "no rebound/guarding",
  "rebound present",
  "guarding present",
  "rigidity present",
  "bs present x4",
  "bs normal",
  "bs hypoactive",
  "bs hyperactive",
  "no hsm",
  "murphy's +ve",
  "murphy's -ve",
  "mcburney's +ve",
  "rovsing's +ve",
  "no cva ttp",
  "cva ttp bilat",
  "cva ttp l",
  "cva ttp r",
  "no hernia",
  "inguinal hernia",
  "dre deferred",
  "dre normal tone",
  "guaiac -ve",
  "guaiac +ve",

  // ── MSK ──
  "full rom",
  "full rom, no pain",
  "limited rom 2/2 pain",
  "limited rom",
  "ttp over",
  "no bony ttp",
  "bony ttp noted",
  "swelling noted",
  "swelling + ecchymosis",
  "effusion present",
  "no deformity",
  "obvious deformity",
  "no crepitus",
  "crepitus noted",
  "joint stable",
  "joint laxity noted",
  "anterior drawer -ve",
  "anterior drawer +ve",
  "lachman -ve",
  "lachman +ve",
  "mcmurray -ve",
  "mcmurray +ve",
  "ottawa ankle rules -ve",
  "ottawa knee rules -ve",
  "slr -ve bilat",
  "slr +ve",
  "no midline spinal ttp",
  "lumbar ttp",
  "paraspinal spasm",
  "nvi distally",
  "5/5 power throughout",
  "motor 5/5 all extremities",
  "wbat",
  "unable to wt bear",
  "ambulating independently",

  // ── Neuro ──
  "neuro: cn ii-xii intact",
  "cn intact",
  "sensation intact bilat",
  "decreased sensation",
  "dtr 2+ symmetric",
  "no focal neuro deficits",
  "focal deficit noted",
  "gait normal/steady",
  "gait ataxic",
  "coordination intact",
  "romberg -ve",
  "romberg +ve",
  "speech clear",
  "dysarthria noted",
  "no pronator drift",
  "pronator drift present",
  "no facial droop",
  "facial droop noted",
  "power intact all 4 limbs",
  "tone normal",

  // ── Skin / Wound ──
  "skin: warm, dry, intact",
  "warm, well-perfused",
  "cool/clammy",
  "pale/diaphoretic",
  "turgor normal",
  "turgor decreased",
  "no rash/lesions",
  "maculopapular rash",
  "urticarial rash",
  "erythema noted",
  "erythema + warmth",
  "ecchymosis noted",
  "lac approx",
  "lac to",
  "abrasion noted",
  "wound clean, no infection",
  "wound edges approximated",
  "surrounding cellulitis",
  "purulent drainage",
  "no purulent drainage",
  "fluctuant area",
  "abscess noted",
  "nvi distal to wound",

  // ── Psych ──
  "psych: appropriate affect",
  "flat affect",
  "labile affect",
  "euthymic mood",
  "depressed mood",
  "tp logical, goal-directed",
  "no si/hi",
  "denies si",
  "denies hi",
  "si present, no plan",
  "safety plan discussed",
  "psych consult obtained",
  "form 1 completed",
  "cooperative w/ assessment",
  "agitated/uncooperative",

  // ── Investigations — Labs ──
  "cbc wnl",
  "cbc: leukocytosis",
  "cbc: anemia",
  "wbc elevated",
  "wbc wnl",
  "hgb wnl",
  "hgb low",
  "plt wnl",
  "lytes wnl",
  "lytes unremarkable",
  "bmp wnl",
  "na wnl",
  "k wnl",
  "cr wnl",
  "cr elevated",
  "egfr wnl",
  "gluc wnl",
  "gluc elevated",
  "hba1c wnl",
  "trop -ve",
  "trop -ve x2",
  "trop -ve x3",
  "trop elevated",
  "serial trops -ve",
  "bnp wnl",
  "bnp elevated",
  "d-dimer -ve",
  "d-dimer elevated",
  "inr therapeutic",
  "inr supratherapeutic",
  "ptt wnl",
  "coags wnl",
  "ua unremarkable",
  "ua +ve for",
  "ua: le+ nit+",
  "ua: micro hematuria",
  "uc sent",
  "upt -ve",
  "upt +ve",
  "uds +ve for",
  "uds -ve",
  "bc obtained",
  "bc sent prior to abx",
  "lactate wnl",
  "lactate elevated",
  "lipase wnl",
  "lipase elevated",
  "lfts wnl",
  "lfts elevated",
  "ast/alt elevated",
  "bili wnl",
  "bili elevated",
  "alp elevated",
  "alb wnl",
  "alb low",
  "crp elevated",
  "crp wnl",
  "esr elevated",
  "procal wnl",
  "procal elevated",
  "vbg wnl",
  "vbg: resp alkalosis",
  "vbg: met acidosis",
  "abg obtained",
  "tsh wnl",
  "asa/apap levels -ve",
  "bhcg -ve",
  "bhcg +ve",
  "etoh level",

  // ── Investigations — Imaging ──
  "cxr nil acute",
  "cxr: no acute cp process",
  "cxr: consolidation",
  "cxr: cardiomegaly",
  "cxr: pulm edema",
  "cxr: pleural effusion",
  "cxr: ptx",
  "cxr: clear lung fields",
  "ct head nil acute",
  "ct head -ve for bleed",
  "ct head shows",
  "cta -ve for pe",
  "cta +ve for pe",
  "cta -ve for dissection",
  "ct a/p shows",
  "ct a/p unremarkable",
  "ct c-spine: no fx",
  "ct c-spine shows",
  "us shows",
  "us abdo unremarkable",
  "us: cholelithiasis",
  "us: no gallstones",
  "us: no free fluid",
  "renal us: hydronephrosis",
  "renal us unremarkable",
  "doppler -ve for dvt",
  "doppler +ve for dvt",
  "xr: no fx or dislocation",
  "xr: no acute bony abnl",
  "xr: fx of",
  "xr: soft tissue swelling",
  "xr: degenerative changes",
  "mri shows",
  "mri pending",
  "imaging pending",
  "reviewed w/ radiology",
  "formal read pending",
  "pocus performed",
  "pocus shows",
  "bedside us: no free fluid",
  "fast -ve",
  "fast +ve",

  // ── ECG ──
  "ecg: nsr",
  "ecg: sinus tachy",
  "ecg: sinus brady",
  "ecg: afib",
  "ecg: afib w/ rvr",
  "ecg: aflutter",
  "ecg: svt",
  "ecg: vtach",
  "ecg: no st changes",
  "ecg: ste in",
  "ecg: std in",
  "ecg: twi in",
  "ecg: no acute ischemic changes",
  "ecg: lbbb",
  "ecg: rbbb",
  "ecg: 1st deg avb",
  "ecg: prolonged qt",
  "ecg: lvh",
  "ecg unchanged from prior",
  "no prior ecg for comparison",

  // ── Assessment / Plan ──
  "clinical picture c/w",
  "presentation c/w",
  "ddx includes",
  "most likely dx",
  "working dx",
  "provisional dx",
  "impression:",
  "assessment:",
  "plan:",

  // ── Treatments / Medications ──
  "ivf initiated",
  "ivf administered",
  "ns bolus given",
  "ns infusion started",
  "lr administered",
  "fluid resus initiated",
  "abx started empirically",
  "abx given",
  "1st dose abx given in ed",
  "analgesia given w/ good effect",
  "pain well controlled",
  "pain partially controlled",
  "adequate analgesia achieved",
  "antiemetic given w/ good effect",
  "antipyretic given",
  "neb ventolin given",
  "neb ipratropium given",
  "steroids given",
  "anticoag initiated",
  "heparin gtt started",
  "lmwh given",
  "ntg given",
  "asa given",
  "pt responded well to tx",
  "sx improved post tx",
  "sx resolved post tx",
  "sx persisted despite tx",
  "repeat assessment improved",
  "repeat vs stable",
  "repeat vs improved",
  "pt reassessed, improving",
  "pt reassessed, stable",
  "tolerating po",
  "unable to tolerate po",

  // ── Common prescriptions (shorthand) ──
  "amox 500mg tid x 7/7",
  "amox 500mg tid x 10/7",
  "amox-clav 875mg bid x 7/7",
  "amox-clav 875mg bid x 10/7",
  "ceph 500mg bid x 7/7",
  "cipro 500mg bid x 7/7",
  "azithro 250mg x 5/7 (z-pack)",
  "doxy 100mg bid x 7/7",
  "clinda 300mg qid x 7/7",
  "metro 500mg tid x 7/7",
  "tmp-smx ds bid x 3/7",
  "tmp-smx ds bid x 7/7",
  "nitrofurantoin 100mg bid x 5/7",
  "fluconazole 150mg x 1",
  "pred 50mg daily x 5/7",
  "pred taper",
  "dex 0.6mg/kg x 1",
  "ibuprofen 400mg tid prn",
  "naproxen 500mg bid prn",
  "acetaminophen 1g qid prn",
  "tylenol #3 1-2 tabs q4-6h prn",
  "tramadol 50mg q6h prn",
  "dimenhydrinate 50mg q4h prn",
  "ondansetron 4mg q6h prn",
  "pantoprazole 40mg daily",
  "omeprazole 20mg daily",
  "cetirizine 10mg daily prn",
  "diphenhydramine 25mg q6h prn",
  "prednisone 40mg daily x 5/7",

  // ── Procedures ──
  "wound irrigated w/ ns",
  "wound irrigated + dressed",
  "wound explored under la",
  "no fb on exploration",
  "sutured w/o complication",
  "wound closed w/ sutures",
  "wound closed w/ staples",
  "wound closed w/ steri-strips",
  "wound closed w/ tissue adhesive",
  "wound left open for secondary intention",
  "la w/ lido",
  "la w/ bupi",
  "digital block performed",
  "regional block performed",
  "procedural sedation performed",
  "splint applied",
  "posterior splint applied",
  "sugar tong splint applied",
  "thumb spica splint applied",
  "walking boot applied",
  "sling applied",
  "buddy taping applied",
  "cast applied",
  "reduction performed",
  "post-reduction xr satisfactory",
  "joint relocated successfully",
  "post-reduction nvi intact",
  "iv access obtained",
  "2x large bore iv placed",
  "central line placed",
  "foley inserted",
  "ngt inserted",
  "chest tube inserted",
  "lp performed",
  "paracentesis performed",
  "thoracentesis performed",
  "i&d performed",
  "packing placed",
  "tdap given",
  "consent obtained",
  "sterile technique",
  "pt tolerated procedure well",
  "no complications",

  // ── Consults ──
  "discussed w/ consultant",
  "discussed w/ attending",
  "discussed w/ on-call",
  "consulted",
  "consultant agrees w/ plan",
  "consultant to see in am",
  "discussed case w/",
  "staff notified",

  // ── Disposition ──
  "plan: admit for w/u + mgmt",
  "plan: admit for obs",
  "plan: admit to medicine",
  "plan: admit to surgery",
  "plan: admit to icu",
  "plan: d/c w/ f/u",
  "plan: d/c home",
  "plan: d/c w/ rx",
  "plan: obs in ed",
  "plan: serial reassessment",
  "medically cleared for d/c",
  "fit for d/c",
  "f/u w/ fp within",
  "f/u w/ specialist",
  "f/u arranged",
  "f/u recommended within",
  "return precautions discussed",
  "return precautions reviewed",
  "d/c instructions provided",
  "pt verbalized understanding",
  "pt agrees w/ plan",
  "d/c in stable condition",
  "d/c in improved condition",
  "admitted to medicine",
  "admitted to surgery",
  "admitted to icu",
  "transferred to",
  "pt left ama",
  "ama documentation completed",
  "risks discussed",
  "rx provided for",
  "med rec completed",
  "advised continue home meds",
  "advised rice",
  "advised return if sx worsen",
  "safety netting given",
  "work note provided",
  "med cert provided",

  // ── Connectors / Transitions ──
  "in addition",
  "furthermore",
  "however",
  "o/w unremarkable",
  "o/w wnl",
  "o/w normal",
  "no other abnl noted",
  "nil acute findings",
  "no evidence of",
  "w/o evidence of",
  "w/o signs of",
  "w/o complication",
  "c/w",
  "suggestive of",
  "concerning for",
  "suspicious for",
  "not c/w",
  "no e/o",
  "no features of",
  "in keeping w/",
  "2/2",
  "likely 2/2",
  "likely r/t",
  "likely d/t",
  "possibly r/t",
  "on background of",
  "given hx of",
  "r/o",
  "has been r/o",
  "cannot r/o",
  "low suspicion for",
  "high suspicion for",
  "clinically stable",
  "clinically improved",
  "bilat",
  "on the l",
  "on the r",
];
