/**
 * Standard medical documentation phrases for ED encounter autocomplete.
 * All lowercase for prefix matching in AutocompleteTextarea.
 */
export const MEDICAL_SUGGESTIONS: string[] = [
  // Presenting complaint / HPI
  "patient presents with",
  "patient presents to the emergency department with",
  "patient reports",
  "patient complains of",
  "chief complaint is",
  "symptoms began approximately",
  "onset was sudden approximately",
  "onset was gradual over the past",
  "pain is described as sharp",
  "pain is described as dull and aching",
  "pain is described as burning",
  "pain is described as pressure-like",
  "pain is described as cramping",
  "pain is constant and non-radiating",
  "pain is intermittent",
  "pain radiates to the",
  "pain worsened by movement",
  "pain worsened by deep inspiration",
  "pain improved with rest",
  "pain improved with analgesics",
  "rates pain as",
  "severity has been worsening",
  "severity has remained stable",
  "associated with nausea and vomiting",
  "associated with fever and chills",
  "associated with shortness of breath",
  "no associated symptoms",
  "denies chest pain or shortness of breath",
  "denies nausea, vomiting, or diarrhea",
  "denies fever, chills, or night sweats",
  "denies headache or visual changes",
  "denies dizziness or lightheadedness",
  "denies syncope or near-syncope",
  "denies loss of consciousness",
  "denies recent trauma or injury",
  "denies recent travel or sick contacts",
  "denies urinary symptoms",
  "denies bowel changes",
  "denies rash or skin changes",
  "denies numbness, tingling, or weakness",
  "denies palpitations",
  "no prior similar episodes",
  "has experienced similar episodes in the past",
  "tried over-the-counter medications without relief",

  // Review of systems
  "review of systems otherwise negative",
  "review of systems positive for",
  "all other systems reviewed and negative",

  // Past medical history
  "past medical history significant for",
  "past medical history includes",
  "no significant past medical history",
  "history of hypertension",
  "history of type 2 diabetes mellitus",
  "history of coronary artery disease",
  "history of atrial fibrillation",
  "history of chronic obstructive pulmonary disease",
  "history of asthma",
  "history of chronic kidney disease",
  "history of congestive heart failure",
  "history of cerebrovascular accident",
  "history of deep vein thrombosis",
  "history of anxiety and depression",
  "history of hypothyroidism",
  "history of gastroesophageal reflux disease",
  "surgical history includes",
  "no prior surgeries",

  // Medications & allergies
  "current medications include",
  "no current medications",
  "allergies include",
  "no known drug allergies",
  "nkda",
  "allergic to penicillin",

  // Social
  "non-smoker",
  "current smoker",
  "former smoker",
  "social alcohol use",
  "denies alcohol use",
  "denies recreational drug use",
  "lives independently at home",
  "lives with family",

  // Vital signs
  "vital signs within normal limits",
  "vital signs stable",
  "vitals notable for tachycardia",
  "vitals notable for hypertension",
  "vitals notable for fever",
  "vitals notable for hypotension",
  "afebrile throughout",

  // General appearance
  "alert and oriented x3",
  "alert and oriented to person, place, and time",
  "appears in no acute distress",
  "appears comfortable at rest",
  "appears uncomfortable but non-toxic",
  "appears acutely ill",
  "appears well-nourished and well-developed",
  "glasgow coma scale 15",

  // HEENT
  "head is normocephalic and atraumatic",
  "pupils equal, round, reactive to light",
  "pupils equal, round, reactive to light and accommodation",
  "extraocular movements intact",
  "no conjunctival injection or discharge",
  "tympanic membranes clear bilaterally",
  "oropharynx clear, no erythema or exudate",
  "mucous membranes moist",
  "no facial asymmetry",

  // Neck
  "no neck stiffness or meningismus",
  "trachea midline",
  "no lymphadenopathy",
  "no jugular venous distension",
  "supple without masses",
  "full range of motion of the neck",

  // Cardiovascular
  "heart sounds normal, regular rate and rhythm",
  "normal s1 and s2, no murmurs, rubs, or gallops",
  "regular rate and rhythm with no extra heart sounds",
  "irregular rhythm consistent with atrial fibrillation",
  "systolic murmur noted at the apex",
  "peripheral pulses intact and symmetric",
  "capillary refill less than 2 seconds",
  "no peripheral edema",
  "bilateral lower extremity edema noted",
  "trace pedal edema bilaterally",

  // Respiratory
  "lungs clear to auscultation bilaterally",
  "good air entry bilaterally",
  "decreased breath sounds at the left base",
  "decreased breath sounds at the right base",
  "bilateral wheezing noted",
  "expiratory wheezing heard bilaterally",
  "fine crackles noted at bilateral bases",
  "coarse crackles noted bilaterally",
  "no respiratory distress",
  "breathing comfortably on room air",
  "oxygen saturation maintained on room air",

  // Abdomen
  "abdomen soft, non-tender, non-distended",
  "abdomen soft with tenderness in the right lower quadrant",
  "abdomen soft with tenderness in the left lower quadrant",
  "abdomen soft with tenderness in the right upper quadrant",
  "abdomen soft with tenderness in the epigastric region",
  "abdomen soft with diffuse tenderness",
  "no rebound tenderness or guarding",
  "positive rebound tenderness",
  "voluntary guarding present",
  "bowel sounds present in all four quadrants",
  "bowel sounds hypoactive",
  "no hepatosplenomegaly",
  "no palpable masses",
  "murphy's sign negative",
  "mcburney's point tenderness present",

  // Musculoskeletal
  "normal range of motion in all extremities",
  "full range of motion without pain",
  "limited range of motion due to pain",
  "tenderness to palpation over the",
  "no tenderness to palpation",
  "swelling noted over the",
  "no deformity noted",
  "no crepitus",
  "joint appears stable",
  "no joint effusion",
  "straight leg raise negative bilaterally",

  // Neurological
  "cranial nerves ii-xii intact",
  "motor strength 5/5 in all extremities",
  "sensation intact to light touch in all dermatomes",
  "deep tendon reflexes 2+ and symmetric",
  "no focal neurological deficits",
  "gait normal and steady",
  "coordination intact with finger-to-nose testing",
  "negative romberg sign",
  "speech clear and fluent",
  "no pronator drift",

  // Skin
  "skin warm, dry, and intact",
  "skin warm and well-perfused",
  "no rash or lesions noted",
  "erythema noted over the",
  "bruising noted over the",
  "laceration approximately",
  "wound appears clean without signs of infection",
  "no cellulitis or abscess noted",
  "neurovascularly intact distally",

  // Psychiatric
  "appropriate affect and behaviour",
  "mood and affect congruent",
  "no suicidal or homicidal ideation",
  "denies suicidal ideation, plan, or intent",

  // Procedures
  "wound irrigated and dressed",
  "sutures placed without complication",
  "wound closure with",
  "local anesthetic administered",
  "splint applied to the",
  "iv access obtained",

  // Investigations
  "cbc within normal limits",
  "complete blood count within normal limits",
  "electrolytes within normal limits",
  "basic metabolic panel within normal limits",
  "creatinine within normal limits",
  "troponin negative x2",
  "serial troponins negative",
  "d-dimer negative",
  "inr within therapeutic range",
  "urinalysis unremarkable",
  "urinalysis positive for",
  "blood cultures obtained and pending",
  "chest x-ray shows no acute abnormality",
  "chest x-ray shows no acute cardiopulmonary process",
  "ct head shows no acute intracranial pathology",
  "ct abdomen and pelvis shows",
  "x-ray shows no fracture or dislocation",
  "x-ray shows a fracture of the",
  "ecg shows normal sinus rhythm",
  "ecg shows sinus tachycardia",
  "ecg shows atrial fibrillation with controlled rate",
  "ecg shows no st changes",
  "ecg unchanged from prior",
  "lactate within normal limits",
  "lipase within normal limits",
  "liver function tests within normal limits",
  "c-reactive protein elevated",
  "point of care ultrasound performed",

  // Assessment & Plan
  "clinical presentation consistent with",
  "differential diagnosis includes",
  "most likely diagnosis is",
  "impression is",
  "plan is to",
  "discussed with consultant",
  "consulted with",
  "iv fluids initiated",
  "normal saline bolus administered",
  "antibiotics initiated empirically",
  "analgesics administered with good effect",
  "patient responded well to treatment",
  "symptoms improved after treatment",
  "plan to admit for further workup and management",
  "plan to discharge with outpatient follow-up",
  "plan to observe in the emergency department",
  "will follow up with family physician within",
  "will follow up with specialist",
  "will monitor for clinical deterioration",
  "patient counseled regarding diagnosis and prognosis",
  "return precautions discussed with patient",
  "discharge instructions provided and reviewed",
  "patient verbalized understanding of discharge plan",
  "patient discharged in stable condition",
  "patient discharged in improved condition",
  "patient admitted to medicine service",
  "patient admitted to surgical service",
  "prescribed",
  "medication reconciliation completed",
  "tetanus vaccination administered",
  "advised to rest and elevate the affected limb",
  "advised to apply ice and compression",
  "advised to return if symptoms worsen or do not improve",
  "safety netting advice given",
];
