/**
 * Standard medical documentation phrases for ED encounter autocomplete.
 * All lowercase for suffix-aware matching in AutocompleteTextarea.
 *
 * The autocomplete engine matches the trailing words of what the user has typed
 * against the beginning of these phrases, so phrases work mid-sentence too.
 * e.g. typing "the pain is described as sh" will match "sharp and stabbing".
 */
export const MEDICAL_SUGGESTIONS: string[] = [
  // ── Presenting complaint / HPI ──
  "patient presents with",
  "patient presents to the emergency department with",
  "patient reports",
  "patient complains of",
  "patient states that",
  "patient was brought in by ambulance",
  "patient was brought in by family",
  "patient walked in to the emergency department",
  "chief complaint is",
  "symptoms began approximately",
  "symptoms have been present for",
  "symptoms have been progressively worsening",
  "symptoms are intermittent in nature",
  "symptoms are constant since onset",
  "onset was sudden approximately",
  "onset was gradual over the past",
  "sudden onset of",
  "gradual onset over the past",
  "acute onset of",
  "woke up this morning with",
  "started earlier today",
  "started yesterday",
  "has been ongoing for several days",
  "has been ongoing for approximately",

  // Pain descriptors
  "pain is described as sharp",
  "pain is described as sharp and stabbing",
  "pain is described as dull and aching",
  "pain is described as burning",
  "pain is described as pressure-like",
  "pain is described as cramping",
  "pain is described as tearing",
  "pain is described as throbbing",
  "pain is described as colicky",
  "pain is described as squeezing",
  "pain is constant and non-radiating",
  "pain is intermittent",
  "pain is pleuritic in nature",
  "pain is positional",
  "pain is worse with movement",
  "pain is worse with deep breathing",
  "pain is worse at night",
  "pain is relieved by rest",
  "pain is relieved by analgesics",
  "pain is relieved by position change",
  "pain is not relieved by rest or analgesics",
  "pain radiates to the",
  "pain radiates to the left arm",
  "pain radiates to the jaw",
  "pain radiates to the back",
  "pain radiates to the right lower quadrant",
  "pain radiates to the groin",
  "pain worsened by movement",
  "pain worsened by deep inspiration",
  "pain worsened by palpation",
  "pain worsened by eating",
  "pain improved with rest",
  "pain improved with analgesics",
  "pain improved with position change",
  "rates pain as",
  "severity has been worsening",
  "severity has remained stable",
  "severity has improved since onset",
  "no change in severity since onset",
  "sharp and stabbing in character",
  "dull and aching in character",
  "burning in character",
  "pressure-like in character",
  "cramping in character",
  "throbbing in character",
  "colicky in character",

  // Associated symptoms
  "associated with nausea and vomiting",
  "associated with nausea but no vomiting",
  "associated with fever and chills",
  "associated with shortness of breath",
  "associated with diaphoresis",
  "associated with dizziness",
  "associated with lightheadedness",
  "associated with palpitations",
  "associated with chest tightness",
  "associated with abdominal bloating",
  "associated with diarrhea",
  "associated with constipation",
  "associated with dysuria and frequency",
  "associated with cough",
  "associated with productive cough",
  "associated with hemoptysis",
  "associated with hematuria",
  "associated with hematemesis",
  "associated with melena",
  "associated with hematochezia",
  "no associated symptoms",

  // Pertinent negatives
  "denies chest pain",
  "denies chest pain or shortness of breath",
  "denies shortness of breath",
  "denies nausea, vomiting, or diarrhea",
  "denies nausea or vomiting",
  "denies fever, chills, or night sweats",
  "denies fever or chills",
  "denies headache or visual changes",
  "denies headache",
  "denies dizziness or lightheadedness",
  "denies syncope or near-syncope",
  "denies loss of consciousness",
  "denies recent trauma or injury",
  "denies recent travel or sick contacts",
  "denies urinary symptoms",
  "denies dysuria or frequency",
  "denies hematuria",
  "denies bowel changes",
  "denies rash or skin changes",
  "denies numbness, tingling, or weakness",
  "denies numbness or tingling",
  "denies weakness",
  "denies palpitations",
  "denies diaphoresis",
  "denies weight loss",
  "denies bleeding or bruising",
  "denies recent antibiotic use",
  "denies recent surgery or hospitalization",
  "denies abdominal pain",
  "denies back pain",
  "denies cough or sputum production",
  "denies hemoptysis",
  "denies photophobia or neck stiffness",
  "denies changes in vision or hearing",
  "denies difficulty swallowing",
  "denies joint pain or swelling",
  "denies swelling or redness",
  "no prior similar episodes",
  "has experienced similar episodes in the past",
  "tried over-the-counter medications without relief",
  "took acetaminophen without improvement",
  "took ibuprofen with mild improvement",

  // Timing and context
  "no precipitating event identified",
  "preceded by",
  "following a fall",
  "following a motor vehicle collision",
  "following heavy lifting",
  "following physical exertion",
  "following a meal",
  "following alcohol consumption",
  "no relieving or aggravating factors identified",
  "worsened since onset",
  "improved since onset",
  "no change since onset",
  "occurred at rest",
  "occurred during exertion",

  // ── Review of systems ──
  "review of systems otherwise negative",
  "review of systems positive for",
  "all other systems reviewed and negative",
  "constitutional: no fever, weight loss, or fatigue",
  "respiratory: no cough, dyspnea, or wheezing",
  "cardiovascular: no chest pain, palpitations, or edema",
  "gastrointestinal: no abdominal pain, nausea, or vomiting",
  "genitourinary: no dysuria, frequency, or hematuria",
  "neurological: no headache, weakness, or numbness",
  "musculoskeletal: no joint pain or swelling",
  "skin: no rash, wounds, or lesions",

  // ── Past medical history ──
  "past medical history significant for",
  "past medical history includes",
  "no significant past medical history",
  "medical history is unremarkable",
  "history of hypertension",
  "history of type 2 diabetes mellitus",
  "history of type 1 diabetes mellitus",
  "history of coronary artery disease",
  "history of myocardial infarction",
  "history of atrial fibrillation",
  "history of chronic obstructive pulmonary disease",
  "history of asthma",
  "history of chronic kidney disease",
  "history of congestive heart failure",
  "history of cerebrovascular accident",
  "history of transient ischemic attack",
  "history of deep vein thrombosis",
  "history of pulmonary embolism",
  "history of anxiety and depression",
  "history of depression",
  "history of anxiety",
  "history of hypothyroidism",
  "history of hyperthyroidism",
  "history of gastroesophageal reflux disease",
  "history of peptic ulcer disease",
  "history of inflammatory bowel disease",
  "history of seizure disorder",
  "history of epilepsy",
  "history of migraine headaches",
  "history of osteoarthritis",
  "history of rheumatoid arthritis",
  "history of gout",
  "history of cancer",
  "history of substance use disorder",
  "history of alcohol use disorder",
  "history of cirrhosis",
  "history of dementia",
  "history of parkinson's disease",
  "history of peripheral vascular disease",
  "history of aortic aneurysm",
  "surgical history includes",
  "previous appendectomy",
  "previous cholecystectomy",
  "previous cesarean section",
  "previous joint replacement",
  "previous coronary artery bypass grafting",
  "previous percutaneous coronary intervention",
  "no prior surgeries",

  // ── Medications & allergies ──
  "current medications include",
  "no current medications",
  "medications as per medication list",
  "on anticoagulation with",
  "on antiplatelet therapy",
  "on insulin therapy",
  "on oral hypoglycemics",
  "on antihypertensives",
  "on beta blocker",
  "on ace inhibitor",
  "on statin therapy",
  "allergies include",
  "no known drug allergies",
  "nkda",
  "allergic to penicillin",
  "allergic to sulfa",
  "allergic to nsaids",
  "allergic to codeine",
  "allergic to morphine",
  "reaction was anaphylaxis",
  "reaction was rash",
  "reaction was gastrointestinal upset",

  // ── Social history ──
  "non-smoker",
  "current smoker",
  "former smoker, quit",
  "social alcohol use",
  "denies alcohol use",
  "denies recreational drug use",
  "denies tobacco use",
  "lives independently at home",
  "lives with family",
  "lives in long-term care facility",
  "lives in assisted living",
  "independent with activities of daily living",
  "requires assistance with activities of daily living",
  "uses a walking aid",
  "wheelchair-bound",
  "retired",

  // ── Vital signs ──
  "vital signs within normal limits",
  "vital signs stable",
  "vital signs repeated and stable",
  "vitals notable for tachycardia",
  "vitals notable for bradycardia",
  "vitals notable for hypertension",
  "vitals notable for hypotension",
  "vitals notable for fever",
  "vitals notable for hypothermia",
  "vitals notable for tachypnea",
  "vitals notable for hypoxia",
  "vitals notable for desaturation",
  "afebrile throughout",
  "temperature",
  "heart rate",
  "blood pressure",
  "respiratory rate",
  "oxygen saturation",
  "oxygen saturation on room air",
  "oxygen saturation on supplemental oxygen",
  "febrile with temperature of",
  "hemodynamically stable",
  "hemodynamically unstable",
  "within normal limits",

  // ── General appearance ──
  "alert and oriented x3",
  "alert and oriented x4",
  "alert and oriented to person, place, and time",
  "alert and oriented to person, place, time, and situation",
  "appears in no acute distress",
  "appears comfortable at rest",
  "appears uncomfortable but non-toxic",
  "appears acutely ill",
  "appears chronically ill",
  "appears anxious",
  "appears diaphoretic",
  "appears pale",
  "appears lethargic",
  "appears well-nourished and well-developed",
  "well-appearing",
  "ill-appearing",
  "in mild distress",
  "in moderate distress",
  "in severe distress",
  "glasgow coma scale 15",
  "glasgow coma scale",

  // ── HEENT ──
  "head is normocephalic and atraumatic",
  "no scalp lacerations or hematomas",
  "pupils equal, round, reactive to light",
  "pupils equal, round, reactive to light and accommodation",
  "pupils 3mm bilaterally and reactive",
  "anisocoria noted",
  "extraocular movements intact",
  "no conjunctival injection or discharge",
  "conjunctival pallor noted",
  "scleral icterus noted",
  "no scleral icterus",
  "tympanic membranes clear bilaterally",
  "tympanic membranes normal bilaterally",
  "hearing intact bilaterally",
  "oropharynx clear, no erythema or exudate",
  "posterior pharynx erythematous with exudate",
  "tonsillar enlargement noted",
  "mucous membranes moist",
  "mucous membranes dry",
  "no oral lesions",
  "no facial asymmetry",
  "nares patent bilaterally",
  "no epistaxis",
  "no battle sign or raccoon eyes",
  "dentition intact",

  // ── Neck ──
  "no neck stiffness or meningismus",
  "neck stiffness noted",
  "meningismus present",
  "trachea midline",
  "no lymphadenopathy",
  "cervical lymphadenopathy noted",
  "anterior cervical lymphadenopathy",
  "no jugular venous distension",
  "jugular venous distension noted",
  "supple without masses",
  "full range of motion of the neck",
  "limited range of motion of the cervical spine",
  "midline cervical spine tenderness",
  "no midline cervical spine tenderness",
  "paraspinal tenderness noted",
  "thyroid normal to palpation",

  // ── Cardiovascular ──
  "heart sounds normal, regular rate and rhythm",
  "normal s1 and s2, no murmurs, rubs, or gallops",
  "regular rate and rhythm",
  "regular rate and rhythm with no extra heart sounds",
  "irregular rhythm",
  "irregular rhythm consistent with atrial fibrillation",
  "irregularly irregular rhythm",
  "systolic murmur noted at the apex",
  "systolic murmur noted at the aortic area",
  "diastolic murmur noted",
  "new murmur noted",
  "no murmurs, rubs, or gallops",
  "peripheral pulses intact and symmetric",
  "peripheral pulses palpable bilaterally",
  "diminished peripheral pulses",
  "dorsalis pedis pulses palpable bilaterally",
  "capillary refill less than 2 seconds",
  "capillary refill less than 3 seconds",
  "capillary refill delayed",
  "no peripheral edema",
  "bilateral lower extremity edema noted",
  "unilateral lower extremity edema noted",
  "pitting edema noted",
  "trace pedal edema bilaterally",
  "1+ pedal edema bilaterally",
  "2+ pedal edema bilaterally",
  "no calf tenderness",
  "calf tenderness noted",
  "negative homan's sign",
  "well-perfused extremities",
  "warm and well-perfused",
  "cool extremities",
  "mottled skin",

  // ── Respiratory ──
  "lungs clear to auscultation bilaterally",
  "clear to auscultation bilaterally",
  "good air entry bilaterally",
  "equal air entry bilaterally",
  "decreased air entry bilaterally",
  "decreased air entry on the left",
  "decreased air entry on the right",
  "decreased breath sounds at the left base",
  "decreased breath sounds at the right base",
  "decreased breath sounds bilaterally",
  "bilateral wheezing noted",
  "diffuse wheezing noted",
  "expiratory wheezing heard bilaterally",
  "inspiratory and expiratory wheezing",
  "scattered wheezing",
  "fine crackles noted at bilateral bases",
  "fine crackles noted at the left base",
  "fine crackles noted at the right base",
  "coarse crackles noted bilaterally",
  "rhonchi noted bilaterally",
  "stridor noted",
  "no respiratory distress",
  "mild respiratory distress",
  "moderate respiratory distress",
  "severe respiratory distress",
  "using accessory muscles of respiration",
  "intercostal retractions noted",
  "breathing comfortably on room air",
  "breathing comfortably on supplemental oxygen",
  "oxygen saturation maintained on room air",
  "oxygen saturation improved with supplemental oxygen",
  "placed on supplemental oxygen via nasal prongs",
  "placed on non-rebreather mask",
  "chest expansion symmetric",
  "dullness to percussion at the base",
  "hyperresonance to percussion",
  "no chest wall tenderness",
  "chest wall tenderness noted",
  "reproducible chest wall tenderness",
  "tracheal deviation noted",
  "no tracheal deviation",

  // ── Abdomen ──
  "abdomen soft, non-tender, non-distended",
  "abdomen soft and non-tender",
  "abdomen distended",
  "abdomen soft with tenderness in the right lower quadrant",
  "abdomen soft with tenderness in the left lower quadrant",
  "abdomen soft with tenderness in the right upper quadrant",
  "abdomen soft with tenderness in the left upper quadrant",
  "abdomen soft with tenderness in the epigastric region",
  "abdomen soft with tenderness in the suprapubic region",
  "abdomen soft with tenderness in the periumbilical region",
  "abdomen soft with diffuse tenderness",
  "right lower quadrant tenderness",
  "left lower quadrant tenderness",
  "right upper quadrant tenderness",
  "left upper quadrant tenderness",
  "epigastric tenderness",
  "suprapubic tenderness",
  "periumbilical tenderness",
  "diffuse abdominal tenderness",
  "no rebound tenderness or guarding",
  "no rebound or guarding",
  "positive rebound tenderness",
  "rebound tenderness present",
  "voluntary guarding present",
  "involuntary guarding present",
  "rigidity noted",
  "bowel sounds present in all four quadrants",
  "bowel sounds present and normal",
  "bowel sounds hypoactive",
  "bowel sounds hyperactive",
  "bowel sounds absent",
  "no hepatosplenomegaly",
  "hepatomegaly noted",
  "splenomegaly noted",
  "no palpable masses",
  "palpable mass noted in the",
  "murphy's sign positive",
  "murphy's sign negative",
  "mcburney's point tenderness present",
  "rovsing's sign positive",
  "rovsing's sign negative",
  "psoas sign positive",
  "obturator sign positive",
  "no costovertebral angle tenderness",
  "costovertebral angle tenderness noted",
  "costovertebral angle tenderness bilaterally",
  "costovertebral angle tenderness on the left",
  "costovertebral angle tenderness on the right",
  "no hernia noted",
  "inguinal hernia noted",
  "rectal exam deferred",
  "rectal exam normal tone, no masses",
  "stool guaiac negative",
  "stool guaiac positive",

  // ── Musculoskeletal ──
  "normal range of motion in all extremities",
  "full range of motion",
  "full range of motion without pain",
  "limited range of motion due to pain",
  "limited range of motion",
  "significantly reduced range of motion",
  "tenderness to palpation over the",
  "tenderness over the",
  "point tenderness over the",
  "no tenderness to palpation",
  "no bony tenderness",
  "bony tenderness noted",
  "swelling noted over the",
  "swelling and ecchymosis noted",
  "effusion noted",
  "no deformity noted",
  "obvious deformity noted",
  "gross deformity noted",
  "no crepitus",
  "crepitus noted",
  "joint appears stable",
  "joint appears unstable",
  "no joint effusion",
  "joint effusion present",
  "no laxity on stress testing",
  "laxity noted on stress testing",
  "anterior drawer test negative",
  "anterior drawer test positive",
  "posterior drawer test negative",
  "lachman test negative",
  "lachman test positive",
  "mcmurray test negative",
  "mcmurray test positive",
  "ottawa ankle rules negative",
  "ottawa ankle rules positive",
  "ottawa knee rules negative",
  "straight leg raise negative bilaterally",
  "straight leg raise positive on the",
  "no midline spinal tenderness",
  "midline spinal tenderness at",
  "lumbar spine tenderness noted",
  "thoracic spine tenderness noted",
  "paraspinal muscle spasm noted",
  "intact distal sensation",
  "intact distal motor function",
  "intact distal pulses",
  "neurovascularly intact",
  "5/5 strength throughout",
  "motor strength 5/5 in all extremities",
  "motor strength 4/5 in the",
  "motor strength 3/5 in the",
  "strength reduced in the",
  "weakness noted in the",
  "grip strength intact bilaterally",
  "weight bearing as tolerated",
  "unable to weight bear",
  "ambulating with difficulty",
  "ambulating independently",

  // ── Neurological ──
  "cranial nerves ii-xii intact",
  "cranial nerves intact",
  "motor strength 5/5 in all extremities",
  "sensation intact to light touch in all dermatomes",
  "sensation intact bilaterally",
  "decreased sensation in the",
  "deep tendon reflexes 2+ and symmetric",
  "deep tendon reflexes symmetric",
  "reflexes normal and symmetric",
  "hyperreflexia noted",
  "hyporeflexia noted",
  "areflexia noted",
  "no focal neurological deficits",
  "focal neurological deficit noted",
  "gait normal and steady",
  "gait unsteady",
  "gait ataxic",
  "unable to assess gait",
  "coordination intact with finger-to-nose testing",
  "finger-to-nose testing normal",
  "dysmetria noted",
  "negative romberg sign",
  "positive romberg sign",
  "speech clear and fluent",
  "speech is slurred",
  "dysarthria noted",
  "aphasia noted",
  "expressive aphasia noted",
  "receptive aphasia noted",
  "no pronator drift",
  "pronator drift present",
  "facial droop noted",
  "no facial droop",
  "nil score on",
  "power intact in all four limbs",
  "tone normal in all four limbs",
  "clonus absent",
  "babinski sign negative bilaterally",
  "babinski sign positive on the",
  "oriented to person only",
  "disoriented to time and place",
  "confused and disoriented",
  "obtunded",
  "responding to verbal stimuli",
  "responding to painful stimuli only",

  // ── Skin ──
  "skin warm, dry, and intact",
  "skin warm and well-perfused",
  "skin cool and clammy",
  "skin pale and diaphoretic",
  "skin turgor normal",
  "skin turgor decreased",
  "no rash or lesions noted",
  "rash noted over the",
  "maculopapular rash noted",
  "petechial rash noted",
  "urticarial rash noted",
  "vesicular rash noted",
  "erythema noted over the",
  "erythema and warmth noted over the",
  "erythema, warmth, and swelling noted",
  "bruising noted over the",
  "ecchymosis noted",
  "laceration approximately",
  "laceration to the",
  "abrasion noted",
  "wound appears clean without signs of infection",
  "wound edges approximated",
  "wound edges irregular",
  "surrounding erythema and induration noted",
  "purulent drainage noted",
  "no purulent drainage",
  "no cellulitis or abscess noted",
  "cellulitis noted with",
  "fluctuant area noted",
  "abscess noted",
  "neurovascularly intact distally",
  "sensation intact distal to the wound",
  "no tendon or bone involvement",
  "no foreign body noted",
  "foreign body removed",
  "intact skin over the area",

  // ── Psychiatric ──
  "appropriate affect and behaviour",
  "affect is flat",
  "affect is blunted",
  "affect is labile",
  "mood is euthymic",
  "mood is depressed",
  "mood is anxious",
  "mood and affect congruent",
  "mood and affect incongruent",
  "thought process logical and goal-directed",
  "thought process disorganized",
  "no perceptual disturbances",
  "auditory hallucinations reported",
  "visual hallucinations reported",
  "paranoid ideation noted",
  "no suicidal or homicidal ideation",
  "denies suicidal ideation, plan, or intent",
  "denies suicidal ideation",
  "denies homicidal ideation",
  "suicidal ideation present without plan",
  "suicidal ideation with plan but no intent",
  "safety plan discussed",
  "psychiatric consultation obtained",
  "patient placed on form 1",
  "judgment and insight intact",
  "judgment and insight impaired",
  "cooperative with assessment",
  "agitated and uncooperative",

  // ── Procedures ──
  "wound irrigated with normal saline",
  "wound irrigated and dressed",
  "wound explored under local anesthesia",
  "no foreign body found on exploration",
  "sutures placed without complication",
  "wound closure with",
  "wound closed with sutures",
  "wound closed with staples",
  "wound closed with steri-strips",
  "wound closed with tissue adhesive",
  "wound left open for secondary intention healing",
  "local anesthetic administered",
  "local anesthesia with lidocaine",
  "local anesthesia with bupivacaine",
  "digital nerve block performed",
  "regional nerve block performed",
  "procedural sedation performed",
  "conscious sedation performed",
  "splint applied to the",
  "posterior splint applied",
  "sugar tong splint applied",
  "thumb spica splint applied",
  "walking boot applied",
  "sling applied",
  "buddy taping applied",
  "cast applied",
  "reduction performed under",
  "reduction performed with adequate analgesia",
  "post-reduction films satisfactory",
  "joint relocated successfully",
  "post-reduction neurovascular status intact",
  "iv access obtained",
  "iv access obtained in the",
  "two large bore iv lines inserted",
  "central line placed",
  "arterial line placed",
  "foley catheter inserted",
  "nasogastric tube inserted",
  "chest tube inserted",
  "lumbar puncture performed",
  "paracentesis performed",
  "thoracentesis performed",
  "abscess incised and drained",
  "incision and drainage performed",
  "packing placed",
  "tetanus vaccination administered",
  "informed consent obtained prior to procedure",
  "procedure performed under sterile technique",
  "patient tolerated procedure well",
  "no immediate complications",

  // ── Investigations — Labs ──
  "cbc within normal limits",
  "complete blood count within normal limits",
  "cbc notable for leukocytosis",
  "cbc notable for anemia",
  "cbc notable for thrombocytopenia",
  "white blood cell count elevated",
  "white blood cell count normal",
  "hemoglobin within normal limits",
  "hemoglobin low at",
  "platelet count within normal limits",
  "electrolytes within normal limits",
  "electrolytes unremarkable",
  "basic metabolic panel within normal limits",
  "metabolic panel unremarkable",
  "sodium within normal limits",
  "potassium within normal limits",
  "hyponatremia noted",
  "hyperkalemia noted",
  "hypokalemia noted",
  "creatinine within normal limits",
  "creatinine elevated at",
  "bun within normal limits",
  "egfr within normal limits",
  "glucose within normal limits",
  "glucose elevated at",
  "glucose low at",
  "hba1c within normal limits",
  "troponin negative",
  "troponin negative x2",
  "troponin negative x3",
  "troponin elevated at",
  "serial troponins negative",
  "serial troponins trending down",
  "bnp within normal limits",
  "bnp elevated at",
  "d-dimer negative",
  "d-dimer elevated at",
  "inr within therapeutic range",
  "inr supratherapeutic at",
  "inr subtherapeutic at",
  "ptt within normal limits",
  "coagulation studies within normal limits",
  "urinalysis unremarkable",
  "urinalysis positive for",
  "urinalysis shows leukocyte esterase and nitrites",
  "urinalysis shows microscopic hematuria",
  "urine culture sent",
  "urine pregnancy test negative",
  "urine pregnancy test positive",
  "urine drug screen positive for",
  "urine drug screen negative",
  "blood cultures obtained",
  "blood cultures obtained and pending",
  "blood cultures sent prior to antibiotics",
  "lactate within normal limits",
  "lactate elevated at",
  "lipase within normal limits",
  "lipase elevated at",
  "liver function tests within normal limits",
  "liver enzymes elevated",
  "ast and alt elevated",
  "bilirubin within normal limits",
  "bilirubin elevated at",
  "alkaline phosphatase elevated",
  "albumin within normal limits",
  "albumin low",
  "c-reactive protein elevated",
  "c-reactive protein within normal limits",
  "esr elevated",
  "procalcitonin within normal limits",
  "procalcitonin elevated",
  "blood gas within normal limits",
  "blood gas shows respiratory alkalosis",
  "blood gas shows metabolic acidosis",
  "blood gas shows respiratory acidosis",
  "venous blood gas obtained",
  "arterial blood gas obtained",
  "thyroid function tests within normal limits",
  "tsh within normal limits",
  "ammonia level within normal limits",
  "ethanol level",
  "acetaminophen and salicylate levels negative",
  "beta hcg negative",
  "beta hcg positive",

  // ── Investigations — Imaging ──
  "chest x-ray shows no acute abnormality",
  "chest x-ray shows no acute cardiopulmonary process",
  "chest x-ray shows consolidation",
  "chest x-ray shows cardiomegaly",
  "chest x-ray shows pulmonary edema",
  "chest x-ray shows pleural effusion",
  "chest x-ray shows pneumothorax",
  "chest x-ray shows clear lung fields",
  "chest x-ray shows patchy opacities",
  "ct head shows no acute intracranial pathology",
  "ct head negative for acute bleed",
  "ct head shows",
  "ct angiography negative for pulmonary embolism",
  "ct angiography positive for pulmonary embolism",
  "ct angiography negative for aortic dissection",
  "ct abdomen and pelvis shows",
  "ct abdomen and pelvis unremarkable",
  "ct c-spine shows no fracture",
  "ct c-spine shows",
  "ultrasound shows",
  "ultrasound of the abdomen unremarkable",
  "ultrasound shows gallstones",
  "ultrasound shows no gallstones",
  "ultrasound shows no free fluid",
  "renal ultrasound shows hydronephrosis",
  "renal ultrasound unremarkable",
  "doppler ultrasound negative for dvt",
  "doppler ultrasound positive for dvt",
  "x-ray shows no fracture or dislocation",
  "x-ray shows no acute bony abnormality",
  "x-ray shows a fracture of the",
  "x-ray shows soft tissue swelling",
  "x-ray shows degenerative changes",
  "mri shows",
  "mri of the brain shows",
  "mri pending",
  "imaging pending",
  "imaging reviewed with radiology",
  "formal radiology read pending",
  "preliminary read consistent with",
  "point of care ultrasound performed",
  "point of care ultrasound shows",
  "bedside ultrasound shows no free fluid",
  "fast exam negative",
  "fast exam positive",

  // ── Investigations — ECG ──
  "ecg shows normal sinus rhythm",
  "ecg shows sinus tachycardia",
  "ecg shows sinus bradycardia",
  "ecg shows atrial fibrillation",
  "ecg shows atrial fibrillation with rapid ventricular response",
  "ecg shows atrial fibrillation with controlled rate",
  "ecg shows atrial flutter",
  "ecg shows supraventricular tachycardia",
  "ecg shows ventricular tachycardia",
  "ecg shows no st changes",
  "ecg shows st elevation in",
  "ecg shows st depression in",
  "ecg shows t wave inversions in",
  "ecg shows no acute ischemic changes",
  "ecg shows left bundle branch block",
  "ecg shows right bundle branch block",
  "ecg shows first degree av block",
  "ecg shows prolonged qt interval",
  "ecg shows left ventricular hypertrophy",
  "ecg unchanged from prior",
  "ecg compared with previous and unchanged",
  "no previous ecg available for comparison",
  "ecg consistent with",

  // ── Assessment & Plan ──
  "clinical presentation consistent with",
  "clinical picture is consistent with",
  "clinical picture is suggestive of",
  "differential diagnosis includes",
  "differential includes",
  "most likely diagnosis is",
  "working diagnosis is",
  "provisional diagnosis of",
  "impression is",
  "assessment is",
  "plan is to",
  "plan is as follows",
  "in summary",
  "in the context of",
  "given the clinical presentation",
  "based on the history and examination",
  "based on the above findings",

  // Consultations
  "discussed with consultant",
  "discussed with attending",
  "discussed with on-call specialist",
  "consulted with",
  "consultation obtained from",
  "specialist recommends",
  "consultant agrees with plan",
  "consultant to see patient in the morning",
  "discussed case with",
  "staff notified",

  // Treatments
  "iv fluids initiated",
  "iv fluids administered",
  "normal saline bolus administered",
  "normal saline infusion started",
  "lactated ringer's solution administered",
  "fluid resuscitation initiated",
  "antibiotics initiated empirically",
  "antibiotics administered",
  "first dose of antibiotics given in the ed",
  "analgesics administered with good effect",
  "analgesics administered",
  "pain management initiated",
  "pain well controlled",
  "pain partially controlled",
  "adequate analgesia achieved",
  "antiemetics administered with good effect",
  "antiemetics administered",
  "antipyretics administered",
  "bronchodilator therapy administered",
  "nebulized salbutamol administered",
  "nebulized ipratropium administered",
  "corticosteroids administered",
  "anticoagulation initiated",
  "heparin infusion started",
  "enoxaparin administered",
  "nitroglycerin administered",
  "aspirin administered",
  "patient responded well to treatment",
  "patient responded partially to treatment",
  "no improvement with initial treatment",
  "symptoms improved after treatment",
  "symptoms resolved after treatment",
  "symptoms persisted despite treatment",
  "repeat assessment shows improvement",
  "repeat assessment shows no change",
  "repeat vitals stable",
  "repeat vitals improved",
  "patient reassessed and improving",
  "patient reassessed and stable",
  "patient tolerating oral intake",
  "patient unable to tolerate oral intake",

  // Disposition
  "plan to admit for further workup and management",
  "plan to admit for observation",
  "plan to admit to medicine service",
  "plan to admit to surgical service",
  "plan to admit to icu",
  "plan to discharge with outpatient follow-up",
  "plan to discharge home",
  "plan to discharge with prescriptions",
  "plan to observe in the emergency department",
  "plan for serial reassessment",
  "plan for repeat investigations",
  "medically cleared for discharge",
  "fit for discharge",
  "will follow up with family physician within",
  "will follow up with family physician in",
  "will follow up with specialist",
  "will follow up in",
  "follow-up arranged with",
  "follow-up recommended within",
  "will monitor for clinical deterioration",
  "will reassess in",
  "serial observations to continue",
  "patient counseled regarding diagnosis and prognosis",
  "patient counseled regarding",
  "risks and benefits discussed",
  "treatment options discussed with patient",
  "shared decision-making with patient",
  "return precautions discussed with patient",
  "return precautions reviewed",
  "discharge instructions provided and reviewed",
  "patient verbalized understanding of discharge plan",
  "patient verbalized understanding",
  "patient agrees with plan",
  "patient discharged in stable condition",
  "patient discharged in improved condition",
  "patient discharged home with follow-up",
  "patient admitted to medicine service",
  "patient admitted to surgical service",
  "patient admitted to icu",
  "patient transferred to",
  "patient left against medical advice",
  "ama documentation completed",
  "risks of leaving discussed with patient",
  "prescribed",
  "prescription provided for",
  "medication reconciliation completed",
  "medications reviewed with patient",
  "new prescription for",
  "advised to continue home medications",
  "advised to rest and elevate the affected limb",
  "advised to apply ice and compression",
  "advised to return if symptoms worsen or do not improve",
  "advised to return to the emergency department if",
  "advised to seek medical attention if",
  "safety netting advice given",
  "work note provided",
  "medical certificate provided",

  // ── Connectors / Transitions (useful mid-sentence) ──
  "in addition",
  "in addition to the above",
  "furthermore",
  "however",
  "otherwise unremarkable",
  "otherwise within normal limits",
  "otherwise normal",
  "no other abnormalities noted",
  "no other concerns at this time",
  "with no acute findings",
  "with no evidence of",
  "without evidence of",
  "without signs of",
  "without complication",
  "without complications",
  "as described above",
  "as noted above",
  "as per protocol",
  "consistent with",
  "suggestive of",
  "concerning for",
  "suspicious for",
  "not consistent with",
  "no evidence of",
  "no signs of",
  "no features of",
  "in keeping with",
  "in the setting of",
  "secondary to",
  "likely secondary to",
  "likely related to",
  "likely due to",
  "possibly related to",
  "on a background of",
  "given the history of",
  "ruled out for",
  "has been ruled out",
  "cannot be ruled out",
  "low clinical suspicion for",
  "high clinical suspicion for",
  "clinically significant",
  "clinically stable",
  "clinically improved",
  "noted bilaterally",
  "noted on the left",
  "noted on the right",
  "bilaterally",
  "on the left side",
  "on the right side",
  "at this time",
  "at present",
  "at the time of assessment",
  "at the time of discharge",
  "prior to discharge",
  "upon reassessment",
  "on reassessment",
  "on repeat assessment",
  "on follow-up",
  "on examination",
  "on inspection",
  "on palpation",
  "on auscultation",
];
